apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: shaikkhaleedaazhari/java-web-app-cicd:latest  # Use your actual Docker image
          ports:
            - containerPort: 8080  # Corrected to match your container's port
