apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80         # External service port
      targetPort: 8080 # Match your containerPort
      nodePort: 30008  # Choose any available port (30000–32767)
  type: NodePort